### ISSUE TITLE
Immutability

### ISSUE THREAD

**Issue by AnakinRaW** [AlamoEngine-Tools/PetroglyphTools#324]
Idk whether i adressed this already.

Personally i aim to design all models to be immutable. For me it's a editors  responsibility to support mutable models the user can modify at runtime, but this library shall only support immutable file modes. E.g. for the new MEG library i already did this, as the old, mutable code for e.g. MegFileHolder, was broken in that regards. 

IDK how about the other file models, as i'm currently not working on them.

Just my thougths

**Comment by gruenwaldlk** [comment]
I followed suit with that idea in my refactoring for the DAT already and we should definitely be consistent with that throughout all libraries.
