### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by AnakinRaW** [AlamoEngine-Tools/PetroglyphTools#330]
For versioning assemblies, i propose to use the already installed Nerdback.GitVersioning tool. 

Therefore we need to remove
```
<AssemblyVersion>
<Version>
<FileVersion>
```

from the project files. 

a version.json file controls which version is used for all packages. 
Or if we want individual versions for each package, each projects get's their own version.json file.

**Comment by gruenwaldlk** [comment]
We definitely want each library as a standalone item (not counting Commons).

I'm not familiar with the Nerdback.GitVersioning tool, but used the documentation by Microsoft for nuget publishing. Are those properly redundant? As far as I'm aware, most tools that rely on the C# projects use those tags for filling info, but don't necessarily work with a nuget dependency that generates them after the fact.
Or more condensed: What advantage does the package provide over the normal versioning?

**Comment by AnakinRaW** [comment]
a couple of advantages i'd say. 
- keeps your project files cleaner, cause you have less tags to manage. 
- Versions are controlled by a single entity (the version.json) file. The tool automatically sets the three tags correclty. Minor Version part get auto-incremented with each deployment. You can see [here](https://github.com/AnakinRaW/CommonUtilities/blob/develop/.github/workflows/release.yml) how you set it up. 
- Also the `FileVersion` tag gets auto-incremented.
- Beta builds can be deployed by branch naming if we configure it that way

> We definitely want each library as a standalone item (not counting Commons).

I don't really understand what you mean. 

I see two plausible options. 
Options 1 (.NET Library Approach): All components are packed separately but they share the same version (e.g. in .NET each assembly currently has version 8.x.x)
Option 2: All components are packed separately **and** they also have individual versions. This makes it more convenient to push updates/fixes to single packages. In that case you'd configure the nuget push to not fail on duplicate version upload, so that you only deploy the lib that was changed.

**Comment by AnakinRaW** [comment]
A question to which i don't really have an answer: 

If all packages have their own versions, how should this repo, meaning [Github Releases ](https://github.com/AlamoEngine-Tools/PetroglyphTools/releases) get versioned?

**Comment by AnakinRaW** [comment]
Yeah, having the same version for all packages kind of loses a bit of felxibility. But personally for me I decided that I don’t care anymore about Version numbers. 
What I mean: we should of course use semVer but I don’t care if a major version increases to 50+. 

I also would encourage not to be hesitant about breaking ApI for new features.

**Comment by AnakinRaW** [comment]
Implemented in #335
